<a href="https://colab.research.google.com/github/Guava99/llm_journey/blob/main/Day9_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DAY 9:   Autograd:Computation Grahp+Chain Rule


Training a neural network has 4 steps repeated thousands of times


*   Step 1- Forward Pass->input goes through model ->get predictions
*   Step 2- Compute loss -> how wrong was the prediction?
*   Step 3- Backward pass -> compute gradients(autograd does this)
*   Step 4- Update weights -> move weights in direction that reduces loss



In [8]:
 import torch
 x=torch.tensor([1.0,2.0,3,0],requires_grad=True)
 # Forward pass -each operation is recorded
 a=x**2
 b=a+2
 c=b*3
 loss=c.sum()
 print("x:",x)
 print(a)
 print(b)
 print(c)
 print("loss:",loss)
 print("grad function:")
 print(loss.grad_fn)
 print(c.grad_fn)
 print(b.grad_fn)
 print(a.grad_fn)
 print(x.grad_fn)
 loss.backward()
 print("\nGradients")
 print("x.grad:",x.grad)



x: tensor([1., 2., 3., 0.], requires_grad=True)
tensor([1., 4., 9., 0.], grad_fn=<PowBackward0>)
tensor([ 3.,  6., 11.,  2.], grad_fn=<AddBackward0>)
tensor([ 9., 18., 33.,  6.], grad_fn=<MulBackward0>)
loss: tensor(66., grad_fn=<SumBackward0>)
grad function:
None

Gradients
x.grad: tensor([ 6., 12., 18.,  0.])


In [16]:
# Build a real neuron from scratch using auto grad :
import torch
# ── A single artificial neuron ────────────────────────
# neuron computes: output = activation(w*x + b)
# w = weight, x = input, b = bias
# activation = ReLU (max(0, value))
torch.manual_seed(42)
#Input-3 features
x=torch.tensor([1.0,2.0,3.0])
w=torch.randn(3,requires_grad=True)
b=torch.randn(1,requires_grad=True)
print(x)
print(w)
print(b)
# Forward pass
z=torch.dot(w,x)+b
print(z)
#Relu activation
output=torch.relu(z)
print("output=relu(z):",output)
#fake loss
loss=output**2
print("loss:",loss)
loss.backward()
print("\n Gradients:")
print("dL/dW",w.grad)
print("dL/db",b.grad)
# manual weight update
learning_rate=0.01
with torch.no_grad():
  w-=learning_rate*w.grad
  b-=learning_rate*b.grad
print("\nUpdated weights:",w)
print("Updated bias:",b)
# Zero gradients — IMPORTANT
# if you don't zero them, next backward() adds to existing gradients
w.grad.zero_()
b.grad.zero_()

# Forward pass again — check if loss reduced
z2 = torch.dot(w, x) + b
output2 = torch.relu(z2)
loss2 = output2 ** 2
print("Loss after update:", loss2.item())
print("Loss reduced?", loss2.item() < loss.item())



tensor([1., 2., 3.])
tensor([0.3367, 0.1288, 0.2345], requires_grad=True)
tensor([0.2303], requires_grad=True)
tensor([1.5280], grad_fn=<AddBackward0>)
output=relu(z): tensor([1.5280], grad_fn=<ReluBackward0>)
loss: tensor([2.3349], grad_fn=<PowBackward0>)

 Gradients:
dL/dW tensor([3.0561, 6.1121, 9.1682])
dL/db tensor([3.0561])

Updated weights: tensor([0.3061, 0.0677, 0.1428], requires_grad=True)
Updated bias: tensor([0.1998], requires_grad=True)
Loss after update: 1.1440880298614502
Loss reduced? True
