<a href="https://colab.research.google.com/github/Guava99/llm_journey/blob/main/pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# ── Creating tensors ──────────────────────────────────

# From a list — same as np.array()
# Output: tensor([1, 2, 3, 4, 5])
t1 = torch.tensor([1, 2, 3, 4, 5])
print("From list:", t1)
print("Shape:", t1.shape)   # torch.Size([5])
print("Dtype:", t1.dtype)   # torch.int64

# Float tensor — most common in ML
# Output: tensor([1., 2., 3.])
t2 = torch.tensor([1.0, 2.0, 3.0])
print("\nFloat tensor:", t2)
print("Dtype:", t2.dtype)   # torch.float32

# Zeros — same as np.zeros()
# Output: 3x4 matrix of 0.0
t3 = torch.zeros(3, 4)
print("\nZeros:\n", t3)

# Ones — same as np.ones()
t4 = torch.ones(2, 5)
print("\nOnes:\n", t4)

# Random normal — same as np.random.randn()
# Output: 3x3 matrix of random floats
t5 = torch.randn(3, 3)
print("\nRandom:\n", t5)

# ── NumPy bridge ──────────────────────────────────────

# Convert NumPy → PyTorch
arr = np.array([1.0, 2.0, 3.0])
t6  = torch.from_numpy(arr)
print("\nFrom NumPy:", t6)

# Convert PyTorch → NumPy
back_to_numpy = t6.numpy()
print("Back to NumPy:", back_to_numpy)

# ── GPU check ─────────────────────────────────────────

# Check if GPU is available (will be False on CPU Colab)
print("\nGPU available:", torch.cuda.is_available())

# Move tensor to GPU if available
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Using device:", device)

t7 = torch.randn(3, 3).to(device)
print("Tensor device:", t7.device)

From list: tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
Dtype: torch.int64

Float tensor: tensor([1., 2., 3.])
Dtype: torch.float32

Zeros:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones:
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Random:
 tensor([[-0.9214,  0.3494, -0.0674],
        [-0.5470, -0.0070, -1.3605],
        [-0.0489,  0.1536, -0.5120]])

From NumPy: tensor([1., 2., 3.], dtype=torch.float64)
Back to NumPy: [1. 2. 3.]

GPU available: False
Using device: cpu
Tensor device: cpu


In [ ]:
import torch
a=torch.tensor([0,1,2,3,4])
b=torch.tensor([6,7,8,9,10])
print("ADD:",a+b)
print("SUB:",a-b)
print("MUL:",a*b)
print("Power:",a**2)


ADD: tensor([ 6,  8, 10, 12, 14])
SUB: tensor([-6, -6, -6, -6, -6])
MUL: tensor([ 0,  7, 16, 27, 40])
Power: tensor([ 0,  1,  4,  9, 16])


In [ ]:
import torch
A = torch.randn(3, 4)   # shape (3, 4)
B = torch.randn(4, 5)   # shape (4, 5)

# Matrix multiply — same as @ in NumPy
C = torch.matmul(A, B)  # shape (3, 5)
print("\nA shape:", A.shape)
print("B shape:", B.shape)
print("C = A@B shape:", C.shape)  # (3, 5)

# Short form — same thing
C2 = A @ B
print("Same?", torch.allclose(C, C2))  # True
x=torch.arange(12,dtype=torch.float32)
print("\nOriginal:",x.shape)
x2=x.reshape(3,4)
print(x2)
x3=x.reshape(2,-1)
print("X3:",x3)
t=torch.randn(3,4)
print("t:",t)
print("dtype:",t.dtype)
print("device:",t.device)
print("Num of elements:",t.numel())


A shape: torch.Size([3, 4])
B shape: torch.Size([4, 5])
C = A@B shape: torch.Size([3, 5])
Same? True

Original: torch.Size([12])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
X3: tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
t: tensor([[-0.7209, -0.3153,  1.7068,  0.3037],
        [-0.1758, -0.3732, -1.0947,  1.4398],
        [ 0.3437,  0.1862, -0.7999, -2.2460]])
dtype: torch.float32
device: cpu
Num of elements: 12


In [13]:
# requires_grad
import torch
x=torch.tensor([2.0],requires_grad=True)
y=x**2
y.backward()
print("dy/dx, where y=x**2,x=2:",x.grad)
x.grad.zero_()
x=torch.tensor([2.0],requires_grad=True)
y=x**2+3*x+1
y.backward()
print(x.grad)
x.grad.zero_()
x=torch.tensor([2.0,3.0,4.0],requires_grad=True)
z=(x**2).sum()
z.backward()
print(x.grad)
print(z)


dy/dx, where y=x**2,x=2: tensor([4.])
tensor([7.])
tensor([4., 6., 8.])
tensor(29., grad_fn=<SumBackward0>)
