In [ ]:
#dot product
import numpy as np
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
manual=1*10+2*20+3*30+4*40
print(manual)
#By numpy way
print("Numpy_way:",np.dot(a,b))
print("Same?",manual==np.dot(a,b))

300
Numpy_way: 300
Same? True


In [ ]:
# Matrix Multiplication
import numpy as np
A=np.array([[1,2],
           [3,4],
           [5,6]])
B=np.array([[7,8,9],
           [10,11,12]])
result1=np.dot(A,B)
result2=A@B
result3=np.matmul(A,B)
print("Shape of A:",A.shape)
print("Shape of B: ",B.shape)
print("Shape of Result2: ",result2.shape)
print("\nResult:\n",result2)
print("\n all same ?",np.allclose(result1,result2))

Shape of A: (3, 2)
Shape of B:  (2, 3)
Shape of Result2:  (3, 3)

Result:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]

 all same ? True


In [ ]:
#In transformers, matrix multiplication is how attention scores are computed:
import numpy as np

# Simulate a tiny attention operation
# 4 tokens, each with embedding size 8
seq_len = 4
embed_dim = 8

# Random token embeddings
X = np.random.randn(seq_len, embed_dim)   # (4, 8)

# Weight matrices for Q, K, V
Wq = np.random.randn(embed_dim, embed_dim)  # (8, 8)
Wk = np.random.randn(embed_dim, embed_dim)  # (8, 8)

# Compute queries and keys
Q = X @ Wq   # (4, 8)
K = X @ Wk   # (4, 8)

# Attention scores — every token attends to every other token
scores = Q @ K.T   # (4, 8) @ (8, 4) = (4, 4)

print("X shape:", X.shape)
print("Q shape:", Q.shape)
print("K shape:", K.shape)
print("Scores shape:", scores.shape)
print("\nAttention scores:\n", scores.round(2))

X shape: (4, 8)
Q shape: (4, 8)
K shape: (4, 8)
Scores shape: (4, 4)

Attention scores:
 [[  44.59   23.    -91.59   77.41]
 [   3.44  -11.77   28.63  -60.56]
 [ -28.83  -25.79   45.62  -38.84]
 [  51.77   38.33 -114.74   71.81]]


In [ ]:
import numpy as np
a=np.random.randn(5,3)
b=np.random.randn(3,7)
c=np.random.randn(7,2)
print((a@b).shape)
print((a@b@c).shape)
print((b.T@a.T).shape)
print(np.allclose((a@b).T,b.T@a.T))

(5, 7)
(5, 2)
(7, 5)
True
